version: 0.2

phases:
  build:
    commands:
      - echo "===== CODEBUILD TEST ====="
      - echo "Source Version:"
      - echo $CODEBUILD_SOURCE_VERSION
      - echo "Webhook Branch (if any):"
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo "Commit ID:"
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
